%YAML 1.2
---
#
# Configures the kind of test station as well as the
# hardware of PC and assigned measurement hardware
#
test_type:  CELL_STACK_TEST  # CORE_TEST, PCBA_TEST
station_id: PCPD1302         # AD Name of PC
line_id:    1                # 1 .. 9

# List of TestSocket configurations
# Minimum is one (the first) socket.
test_sockets:
  "1":
    resource_strings:
      scanner:      "192.168.1.83:2000"
      led_analyzer: "192.168.1.83:3000"
      daq:          "TCPIP0::192.168.1.53::inst0::INSTR"
      ncd_ethi2c:   "192.168.1.55:3000"
      eeprom:       "1:7"  # "<MUX-Channel>:<7-bit slave addess>"
  "2":
    resource_strings:
      scanner:      "192.168.1.84:2000"
      led_analyzer: "192.168.1.84:3000"
      daq:          "TCPIP0::192.168.1.54::inst0::INSTR"
      ncd_ethi2c:   "192.168.1.55:3000"
      eeprom:       "1:7"  # "<MUX-Channel>:<7-bit slave addess>"
  "3":
    resource_strings:
      scanner:      "192.168.1.84:2000"
      led_analyzer: "192.168.1.84:3000"
      daq:          "TCPIP0::192.168.1.55::inst0::INSTR"
      ncd_ethi2c:   "192.168.1.55:3000"
      eeprom:       "1:7"  # "<MUX-Channel>:<7-bit slave addess>"


# END OF FILE