# configure database which will be expected to be a MySQL/MariaDB type;
sourceDatabase:
    servertype: "mysql+pymysql" # pure python
    serverhost: "172.22.2.99"
    database:   "protocol"
    login:      "dsp"
    password:   "fdZD9djESaYuVbZ"
    encoding:   "utf8"
