# configure database which will be expected to be a MySQL/MariaDB type;
sourceDatabase:
    servertype: "mysql+pymysql" # pure python
    serverhost: "sv-production-vn"
    database:   "station_users"
    login:      "teststand"
    password:   "gedoehns!"
    encoding:   "utf8"
